### PR TITLE
Include the real name for the user list

### PR DESCRIPTION
**Pull request by victori**
Had a request to add real names on the user-list. Makes sense for certain teams.

### CODE REVIEW

**Comment by victori** [comment]
Eion,

Thanks for the suggestion, as you can tell I don’t do any C/C++ development. Just Java, Ruby, Python and friends.

- Victor

**Comment by EionRobb** [comment]
Oh, in that case in future, never mix code that works with bytes (malloc, sprintf) with code that works with characters (g_utf8_strlen)
What you currently have there will try to allocate less memory than needed, (eg 40 chinese characters  == 80 bytes) and then try to write all the memory not not enough space, overflowing the memory and if you're lucky it will only crash the app, but otherwise will overwrite memory of data around it causing all kinds of chaos :)

**Comment by xypd** [comment]
> overflowing the memory and if you're lucky it will only crash the app

Funny, not sure if this was my issue ... but Adium did crash when I tried sending a message to a contact. Probably should have reported it.

**Comment by victori** [comment]
Hmm, I tried it but it kept segfaulting. 

https://github.com/victori/slack-libpurple/commit/fd6d659184802d22f5befe33d67d6076d587ca4f

- Victor

**Comment by dylex** [comment]
There do not seem to be any changes left here. Closing.

**Pull request closed without merging**
